# vim:sw=2:et:

distro: bionic

sudo: false
language: erlang
notifications:
  email:
    recipients:
      - alerts@rabbitmq.com
    on_success: never
    on_failure: always
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu bionic contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - awscli
      # Use Elixir from Erlang Solutions. The provided Elixir is
      # installed with kiex but is old. We also can't use kiex to
      # install a newer one because of GitHub API rate limiting.
      - elixir=1.9.2-1
cache:
  apt: true
env:
  global:
    - secure: GSpypPCRiJGa9bSlSseoQtnrSWqER9LP6L42204omhPVIXXXg0Yksdfjh5iDropylZBO86A1XBQcWPgb7kFZFNDZfKe6qVefuoTMKITAUW7qxihhFWJTqL0Y3Hbsadtc5OQ69Uu/nKL2V820pQ93ksyJApBRVoWLb66uxzkyvbY2bjEL2qpnnKjh232IAgI+wiHSo95lrg+zx/GMNafdU4IsGMJ7IgLK2frKynYM7Qg2iVkQw7+//rnZXhtIGY5LtMtlF2sgGkFmcAg8H/cIhI2cCuam3FLnDZp1eWoYBs12Y7Bsthik2culpHaV21mzankyO3KedBNKUwNhDVz02wzBmbakxBUTxLHi91x2t5GLrB8qk5deBmSaMuqq1XgO2qVWi1/oJ9FKiaRgJ2q9T7ZhgPmwj9WsAhrMuCTWbECD+Z/xEJL13OGTfpD9gcQ/emZWLmbinf1WGRWFMnin1QedLtzyXChItXdnbVdyBENm0XaHEj5i2SPpin4xw3P9f7GS/nh9UP2qaTp18Vtwj/Ub4MyXtWz/rR0E8YjDf7llGKl0yiG/0IqR3dyJ0KKq2MU9qbosSYHZOoygFtKLKfKpCNW6QXTfTbylsaw45mnQwwhor1+9VgpyysDET8B1XJAkgjMkbS+cKvLwcxJxy6UyqZA27P2pIuZOWfqCCPo=
    - secure: DFzxIJaJJVWc4h5baROCRS6+graLmXjPVXGflx/eTWXhWHMvcSPnRCNEbIGhwbmX1OE+J9SogOjAi6Ga/9l0x5K/n5pQqsazc8gbmXXLcExmskzS/k0lfHKD0rCblTv64XOiYIGkQzGzZfOL8MeDROmqOdQNrIv7JT9Jxsdg9ycivfdb86hLWonyyUQTJbDTKzfq97JDKFFiuA4g3xN0UMrX+/R3qx9ajoKrPmf5UTrFSfSWvCPB02Edj5of9gnIYeCusy/DgBhSNygMQ50A0RqrBRhXjwJQNvJKANYGyk7FzSDBGH0nPZYjOVH61LNjyz/cVqdUddkUOGEOGTcxObJwUV7WfxH75AHCsrtD4OZZT95Z7kxLT4MGhDTqQWGI3HHNQxhuo3shfzvU2g8mXlGyilly2Gfygsau+de9CAmUUbtzTJ8nXdxz54DB8rrhGDA45yjt2trgKEQwPP+9gcOm/4rpJb/AOb5eHttoyroKmXL7CqhAd2y1+U0pR4oyX3f4IJyQG794vPv83K+yaUTc8mzRjP3hVJnt9ugJXVhQw4vsOnOeQ7eYuhNBNLTbk3eVEK10FF9C8JcUVz/Ij/viTHjT+RcQXdukBE+p0cDCyz3wRbF5X69ABl3i5u0TxjkCz5E3CmZ4YfLSPv2dDweqSwFvBjATe6wD04PB74Y=

otp_release:
  - "21.3"
  - "22.1"

before_script:
  # The checkout made by Travis is a "detached HEAD" and branches
  # information is missing. Our Erlang.mk's git_rmq fetch method relies
  # on it, so we need to restore it.
  #
  # We simply fetch master and, if it exists, v3.8.x branches. A branch
  # is created, pointing to the detached HEAD.
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream v3.8.x:v3.8.x || :
    git fetch upstream master:master || :
  # Make sure we use Elixir from Erlang Solutions and not kiex.
  - |
    echo YES | kiex implode
    elixir --version
    elixir --version | grep -q 'Elixir 1.9'

script:
  - make xref
  - make tests

after_failure:
  - |
    cd "$TRAVIS_BUILD_DIR"
    if test -d logs && test "$AWS_ACCESS_KEY_ID" && test "$AWS_SECRET_ACCESS_KEY"; then
      archive_name="$(basename "$TRAVIS_REPO_SLUG")-$TRAVIS_JOB_NUMBER"

      tar -c --transform "s/^logs/${archive_name}/" -f - logs | \
        xz > "${archive_name}.tar.xz"

      aws s3 cp "${archive_name}.tar.xz" s3://server-release-pipeline/travis-ci-logs/ \
        --region eu-west-1 \
        --acl public-read
    fi
